[package]
name = "lattice-desktop"
description = "Lattice desktop client"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "lattice_desktop"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
tauri = { version = "=2.11.6", features = [] }

[lints]
workspace = true
