[package]
name = "lattice-transport"
description = "Bounded platform transport orchestration"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
lattice-platform = { path = "../lattice-platform" }
tokio = { version = "=1.53.1", features = ["io-util", "net", "rt", "macros", "sync"] }

[lints]
workspace = true
