[package]
name = "lattice-events"
description = "Lattice authenticated events and reducers"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true


[dependencies]
lattice-identity = { path = "../lattice-identity", version = "=0.1.0" }
lattice-protocol = { path = "../lattice-protocol", version = "=0.1.0" }
[lints]
workspace = true
